export const UserTypes = {
  // update userDetails
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  REQUEST_UPDATE_USER_DATA: "REQUEST_UPDATE_USER_DATA",
  SUCCESS_UPDATE_USER_DATA: "SUCCESS_UPDATE_USER_DATA",
  FAILURE_UPDATE_USER_DATA: "FAILURE_UPDATE_USER_DATA",

  // create userDetails
  CREATE_USER_DETAILS: "CREATE_USER_DETAILS",
  REQUEST_CREATE_USER_DETAILS: "REQUEST_CREATE_USER_DETAILS",
  SUCCESS_CREATE_USER_DETAILS: "SUCCESS_CREATE_USER_DETAILS",
  FAILURE_CREATE_USER_DETAILS: "FAILURE_CREATE_USER_DETAILS",

  // login users
  LOGIN_USER: "LOGIN_USER",
  REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
  SUCCESS_LOGIN_USER: "SUCCESS_LOGIN_USER",
  FAILURE_LOGIN_USER: "FAILURE_LOGIN_USER",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};

export const DonationTypes = {
  // add donations to list
  ADD_DONATION: "ADD_DONATION",
  REQUEST_ADD_DONATION: "REQUEST_ADD_DONATION",
  SUCCESS_ADD_DONATION: "SUCCESS_ADD_DONATION",
  FAILURE_ADD_DONATION: "FAILURE_ADD_DONATION",

  // fetch all donations
  FETCH_DONATION_DATA: "FETCH_DONATION_DATA",
  REQUEST_FETCH_DONATION_DATA: "REQUEST_DONATION_DATA",
  SUCCESS_FETCH_DONATION_DATA: "SUCCESS_FETCH_DONATION_DATA",
  FAILURE_FETCH_DONATION_DATA: "FAILURE_FETCH_DONATION_DATA",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};
