export const UserTypes = {
  // update userDetails
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  REQUEST_UPDATE_USER_DATA: "REQUEST_UPDATE_USER_DATA",
  SUCCESS_UPDATE_USER_DATA: "SUCCESS_UPDATE_USER_DATA",
  FAILURE_UPDATE_USER_DATA: "FAILURE_UPDATE_USER_DATA",

  // create userDetails
  CREATE_USER_DETAILS: "CREATE_USER_DETAILS",
  REQUEST_CREATE_USER_DETAILS: "REQUEST_CREATE_USER_DETAILS",
  SUCCESS_CREATE_USER_DETAILS: "SUCCESS_CREATE_USER_DETAILS",
  FAILURE_CREATE_USER_DETAILS: "FAILURE_CREATE_USER_DETAILS",

  // login users
  LOGIN_USER: "LOGIN_USER",
  REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
  SUCCESS_LOGIN_USER: "SUCCESS_LOGIN_USER",
  FAILURE_LOGIN_USER: "FAILURE_LOGIN_USER",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};

export const DonationTypes = {
  // add donations to list
  ADD_DONATION: "ADD_DONATION",
  REQUEST_ADD_DONATION: "REQUEST_ADD_DONATION",
  SUCCESS_ADD_DONATION: "SUCCESS_ADD_DONATION",
  FAILURE_ADD_DONATION: "FAILURE_ADD_DONATION",

  // fetch all donations
  FETCH_DONATION_DATA: "FETCH_DONATION_DATA",
  REQUEST_FETCH_DONATION_DATA: "REQUEST_DONATION_DATA",
  SUCCESS_FETCH_DONATION_DATA: "SUCCESS_FETCH_DONATION_DATA",
  FAILURE_FETCH_DONATION_DATA: "FAILURE_FETCH_DONATION_DATA",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};

export const DonationRequestTypes = {
  // create requests
  CREATE_DONATION_REQUESTS: "CREATE_REQUESTS",
  REQUEST_CREATE_DONATION_REQUESTS: "REQUEST_CREATE_REQUESTS",
  SUCCESS_CREATE_DONATION_REQUESTS: "SUCCESS_CREATE_REQUESTS",
  FAILURE_CREATE_DONATION_REQUESTS: "FAILURE_CREATE_REQUESTS",

  // fecth all requests
  FETCH_DONATION_REQUESTS: "FETCH_REQUESTS",
  REQUEST_FETCH_DONATION_REQUESTS: "REQUEST_FETCH_REQUESTS",
  SUCCESS_FETCH_DONATION_REQUESTS: "SUCCESS_FETCH_REQUESTS",
  FAILURE_FETCH_DONATION_REQUESTS: "FAILURE_FETCH_REQUESTS",

  //withdraw donation requests
  WITHDRAW_DONATION_REQUESTS: "WITHDRAW_DONATION_REQUESTS",
  REQUEST_WITHDRAW_DONATION_REQUESTS: "REQUEST_WITHDRAW_DONATION_REQUESTS",
  SUCCESS_WITHDRAW_DONATION_REQUESTS: "SUCCESS_WITHDRAW_DONATION_REQUESTS",
  FAILURE_WITHDRAW_DONATION_REQUESTS: "FAILURE_WITHDRAW_DONATION_REQUESTS",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};

export const ApprovementTypes = {
  // fetch all requests
  FETCH_APPROVALS: "FETCH_APPROVALS",
  REQUEST_FETCH_APPROVALS: "REQUEST_FETCH_APPROVALS",
  SUCCESS_FETCH_APPROVALS: "SUCCESS_FETCH_APPROVALS",
  FAILURE_FETCH_APPROVALS: "FAILURE_FETCH_APPROVALS",

  // fetch requester details
  FETCH_REQUESTER_DETAILS: "FETCH_REQUESTER_DETAILS",
  REQUEST_FETCH_REQUESTER_DETAILS: "REQUEST_FETCH_REQUESTER_DETAILS",
  SUCCESS_FETCH_REQUESTER_DETAILS: "SUCCESS_FETCH_REQUESTER_DETAILS",
  FAILURE_FETCH_REQUESTER_DETAILS: "FAILURE_FETCH_REQUESTER_DETAILS",

  // approve/decline donation requests
  APPROVE_DONATION_REQUESTS: "APPROVE_DONATION_REQUESTS",
  REQUEST_APPROVE_DONATION_REQUESTS: "REQUEST_APPROVE_DONATION_REQUESTS",
  SUCCESS_APPROVE_DONATION_REQUESTS: "SUCCESS_APPROVE_DONATION_REQUESTS",
  FAILURE_APPROVE_DONATION_REQUESTS: "FAILURE_APPROVE_DONATION_REQUESTS",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};

export const DashboardTypes = {
  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",

  //fetch dashboard data
  FETCH_DASHBOARD_DATA: "FETCH_DASHBOARD_DATA",
  REQUEST_FETCH_DASHBOARD_DATA: "REQUEST_FETCH_DASHBOARD_DATA",
  SUCCESS_FETCH_DASHBOARD_DATA: "SUCCESS_FETCH_DASHBOARD_DATA",
  FAILURE_FETCH_DASHBOARD_DATA: "FAILURE_FETCH_DASHBOARD_DATA",
};
