export const UserTypes = {
  // fetch userDetails
  FETCH_USER_DETAILS: "FETCH_USER_DETAILS",
  REQUEST_FETCH_USER_DETAILS: "REQUEST_FETCH_USER_DETAILS",
  SUCCESS_FETCH_USER_DETAILS: "SUCCESS_FETCH_USER_DETAILS",
  FAILURE_FETCH_USER_DETAILS: "FAILURE_FETCH_USER_DETAILS",

  // update userDetails
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  REQUEST_UPDATE_USER_DATA: "REQUEST_UPDATE_USER_DATA",
  SUCCESS_UPDATE_USER_DATA: "SUCCESS_UPDATE_USER_DATA",
  FAILURE_UPDATE_USER_DATA: "FAILURE_UPDATE_USER_DATA",

  // create userDetails
  CREATE_USER_DETAILS: "CREATE_USER_DETAILS",
  REQUEST_CREATE_USER_DETAILS: "REQUEST_CREATE_USER_DETAILS",
  SUCCESS_CREATE_USER_DETAILS: "SUCCESS_CREATE_USER_DETAILS",
  FAILURE_CREATE_USER_DETAILS: "FAILURE_CREATE_USER_DETAILS",

  // login users
  LOGIN_USER: "LOGIN_USER",
  REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
  SUCCESS_LOGIN_USER: "SUCCESS_LOGIN_USER",
  FAILURE_LOGIN_USER: "FAILURE_LOGIN_USER",

  // reset success and err messages
  RESET_MESSAGE: "RESET_MESSAGE",
};
